import {
  DirectionId,
  Location,
  RouteSeed,
  StopSeed,
} from './transit.types';
import { GENERATED_ROAD_POLYLINES } from './generated-road-polylines';

function point(lat: number, lng: number): Location {
  return { lat, lng };
}

function stop(
  stopId: string,
  stopName: string,
  lat: number,
  lng: number,
  landmark: string,
  areaDescription: string,
  isMajorStop: boolean,
  isInterchange: boolean,
  zone: StopSeed['zone'],
): StopSeed {
  return {
    stopId,
    stopName,
    location: point(lat, lng),
    landmark,
    areaDescription,
    isMajorStop,
    isInterchange,
    zone,
  };
}

export const BANGKOK_STOPS: StopSeed[] = [
  stop(
    'stop_mochit_bus_terminal',
    'Mo Chit Bus Terminal',
    13.8137,
    100.5499,
    'Mo Chit 2',
    'Northern Bangkok intercity and BMTA terminal near Chatuchak',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_chatuchak_park',
    'Chatuchak Park',
    13.8023,
    100.5537,
    'MRT Chatuchak Park / BTS Mo Chit',
    'Major BTS and MRT interchange beside Chatuchak Weekend Market',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_saphan_khwai',
    'Saphan Khwai',
    13.7937,
    100.5497,
    'BTS Saphan Khwai',
    'Phahon Yothin corridor near local markets and office blocks',
    false,
    true,
    'arterial',
  ),
  stop(
    'stop_ari',
    'Ari',
    13.7797,
    100.5446,
    'BTS Ari',
    'Dense mixed-use district with offices, cafes, and residences',
    true,
    true,
    'cbd',
  ),
  stop(
    'stop_sanam_pao',
    'Sanam Pao',
    13.7723,
    100.5421,
    'BTS Sanam Pao',
    'Army and hospital zone along Phahon Yothin Road',
    false,
    true,
    'cbd',
  ),
  stop(
    'stop_victory_monument',
    'Victory Monument',
    13.7638,
    100.5383,
    'Victory Monument BTS',
    'High-turnover transfer area for city buses and vans',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_ratchathewi',
    'Ratchathewi',
    13.7515,
    100.5309,
    'BTS Ratchathewi',
    'Inner-city corridor connecting Pratunam and Siam',
    true,
    true,
    'cbd',
  ),
  stop(
    'stop_siam',
    'Siam',
    13.7457,
    100.5347,
    'Siam BTS Interchange',
    'Bangkok retail core with heavy pedestrian demand all day',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_samyan',
    'Sam Yan',
    13.7312,
    100.5289,
    'MRT Sam Yan / Samyan Mitrtown',
    'University and office district on Rama IV corridor',
    true,
    true,
    'cbd',
  ),
  stop(
    'stop_hua_lamphong',
    'Hua Lamphong',
    13.7373,
    100.5168,
    'MRT Hua Lamphong',
    'Historic rail terminal area near Yaowarat edge',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_memorial_bridge',
    'Memorial Bridge',
    13.7396,
    100.4978,
    'Memorial Bridge / Pak Khlong Talat',
    'Historic river crossing between old city corridors and the Thonburi side',
    true,
    false,
    'river_crossing',
  ),
  stop(
    'stop_khlong_san',
    'Khlong San',
    13.7306,
    100.5072,
    'Khlong San riverside corridor',
    'Riverside commercial frontage before buses fan out toward Wongwian Yai',
    true,
    false,
    'river_crossing',
  ),
  stop(
    'stop_pinklao',
    'Pinklao',
    13.7774,
    100.4771,
    'Central Pinklao',
    'West-side commercial zone and bridge approach',
    true,
    false,
    'river_crossing',
  ),
  stop(
    'stop_siriraj',
    'Siriraj Hospital',
    13.7589,
    100.4854,
    'Siriraj Hospital',
    'Major hospital frontage on the Thonburi side',
    true,
    false,
    'river_crossing',
  ),
  stop(
    'stop_democracy_monument',
    'Democracy Monument',
    13.7568,
    100.5018,
    'Ratchadamnoen Klang',
    'Old city civic corridor with event-related traffic',
    true,
    false,
    'cbd',
  ),
  stop(
    'stop_national_stadium',
    'National Stadium',
    13.7465,
    100.5282,
    'BTS National Stadium / MBK',
    'Retail and stadium frontage beside MBK Center',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_chitlom',
    'Chit Lom',
    13.7441,
    100.5446,
    'BTS Chit Lom',
    'Premium retail and office district on Ploenchit Road',
    true,
    true,
    'cbd',
  ),
  stop(
    'stop_asok',
    'Asok',
    13.7375,
    100.5601,
    'BTS Asok / MRT Sukhumvit',
    'High-demand interchange between Sukhumvit and MRT blue line',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_phrom_phong',
    'Phrom Phong',
    13.7307,
    100.5697,
    'BTS Phrom Phong',
    'Dense residential and retail stretch on Sukhumvit',
    true,
    true,
    'cbd',
  ),
  stop(
    'stop_ekkamai',
    'Ekkamai',
    13.7196,
    100.5853,
    'BTS Ekkamai / Eastern Bus Terminal',
    'Eastern gateway with coach terminal and heavy transfers',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_phra_khanong',
    'Phra Khanong',
    13.7151,
    100.5922,
    'BTS Phra Khanong',
    'Mixed residential and office corridor before On Nut',
    false,
    true,
    'arterial',
  ),
  stop(
    'stop_on_nut',
    'On Nut',
    13.7056,
    100.6016,
    'BTS On Nut',
    'Large neighborhood hub with market and feeder services',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_bang_kapi',
    'Bang Kapi',
    13.7651,
    100.6414,
    'Bang Kapi District',
    'Eastern residential center and shopping area',
    true,
    false,
    'suburban',
  ),
  stop(
    'stop_the_mall_bang_kapi',
    'The Mall Bang Kapi',
    13.7668,
    100.6435,
    'The Mall Bang Kapi',
    'Large shopping mall and neighborhood transfer point',
    true,
    false,
    'suburban',
  ),
  stop(
    'stop_ramkhamhaeng_24',
    'Ramkhamhaeng 24',
    13.7486,
    100.6108,
    'Ramkhamhaeng University area',
    'University frontage and apartment district on Ramkhamhaeng Road',
    false,
    false,
    'arterial',
  ),
  stop(
    'stop_rama_9',
    'Rama 9',
    13.7579,
    100.5657,
    'MRT Phra Ram 9 / Central Rama 9',
    'Major office and shopping district on Ratchadaphisek',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_pratunam',
    'Pratunam',
    13.7505,
    100.5402,
    'Pratunam Market',
    'Wholesale retail area with persistent curbside congestion',
    true,
    false,
    'cbd',
  ),
  stop(
    'stop_wongwian_yai',
    'Wongwian Yai',
    13.7211,
    100.4959,
    'BTS Wongwian Yai',
    'Thonburi rail and bus transfer zone',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_bang_sue_grand_station',
    'Bang Sue Grand Station',
    13.8034,
    100.5338,
    'Krung Thep Aphiwat Central Terminal',
    'Northern rail gateway with regional and urban interchange',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_kasetsart_university',
    'Kasetsart University',
    13.8472,
    100.5718,
    'BTS Kasetsart University',
    'University campus corridor with heavy student and staff demand',
    true,
    true,
    'arterial',
  ),
  stop(
    'stop_bang_khen',
    'Bang Khen',
    13.8738,
    100.5967,
    'Phahon Yothin / Bang Khen junction',
    'Northern Bangkok corridor with military offices and local housing estates',
    false,
    false,
    'arterial',
  ),
  stop(
    'stop_lak_si',
    'Lak Si',
    13.8886,
    100.5794,
    'IT Square Lak Si',
    'Busy northern interchange corridor near government offices and suburban feeders',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_don_mueang_airport',
    'Don Mueang Airport',
    13.9137,
    100.6021,
    'Don Mueang International Airport',
    'Airport frontage with all-day demand from travelers and airport staff',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_rangsit_market',
    'Rangsit Market',
    13.9892,
    100.6188,
    'Future Park / Rangsit market zone',
    'Northern suburban terminal area with high commuter turnover',
    true,
    false,
    'suburban',
  ),
  stop(
    'stop_thammasat_rangsit',
    'Thammasat Rangsit',
    14.0714,
    100.6014,
    'Thammasat University Rangsit',
    'Northern university and bus terminal zone with high peak commuter demand',
    true,
    true,
    'suburban',
  ),
  stop(
    'stop_fashion_island',
    'Fashion Island',
    13.8261,
    100.6786,
    'Fashion Island / Outer Ring',
    'Eastern Bangkok retail hub on Ram Inthra corridor',
    true,
    false,
    'suburban',
  ),
  stop(
    'stop_minburi_market',
    'Min Buri Market',
    13.8127,
    100.7311,
    'Min Buri Market',
    'Large eastern terminal area with local feeder buses and market traffic',
    true,
    false,
    'suburban',
  ),
  stop(
    'stop_ha_yaek_lat_phrao',
    'Ha Yaek Lat Phrao',
    13.816,
    100.5617,
    'BTS Ha Yaek Lat Phrao / MRT Phahon Yothin',
    'Large mall and interchange node beside Union Mall',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_samrong',
    'Samrong',
    13.6454,
    100.5956,
    'BTS Samrong',
    'Major eastern interchange between Sukhumvit corridor and Samut Prakan feeders',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_pak_nam',
    'Pak Nam',
    13.6022,
    100.5972,
    'BTS Pak Nam / Samut Prakan civic center',
    'Historic Samut Prakan center with strong all-day transfer demand',
    true,
    true,
    'suburban',
  ),
  stop(
    'stop_lat_phrao',
    'Lat Phrao',
    13.8061,
    100.5731,
    'Lat Phrao Intersection',
    'Busy Ratchadaphisek corridor near office towers and condos',
    true,
    false,
    'arterial',
  ),
  stop(
    'stop_sutthisan',
    'Sutthisan',
    13.7864,
    100.5745,
    'MRT Sutthisan',
    'Dense mixed-use corridor with strong commuter demand',
    false,
    true,
    'arterial',
  ),
  stop(
    'stop_huai_khwang',
    'Huai Khwang',
    13.7783,
    100.5737,
    'MRT Huai Khwang',
    'Busy nightlife and office district on Ratchadaphisek Road',
    true,
    true,
    'arterial',
  ),
  stop(
    'stop_thailand_cultural_centre',
    'Thailand Cultural Centre',
    13.7662,
    100.5716,
    'MRT Thailand Cultural Centre',
    'Major employment and event node with mall traffic',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_sanam_luang',
    'Sanam Luang',
    13.7551,
    100.4932,
    'Sanam Luang / Thammasat',
    'Historic old city bus hub serving civic events and university travel',
    true,
    true,
    'cbd',
  ),
  stop(
    'stop_udom_suk',
    'Udom Suk',
    13.6801,
    100.6097,
    'BTS Udom Suk',
    'Eastern Sukhumvit interchange serving neighborhood feeders and expressway access',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_bang_na',
    'Bang Na',
    13.6686,
    100.6352,
    'BTS Bang Na',
    'Bang Na trade and exhibition corridor with strong commuter demand',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_mega_bangna',
    'Mega Bangna',
    13.6467,
    100.6806,
    'Mega Bangna',
    'Large eastern retail hub with feeder vans and suburban demand',
    true,
    false,
    'suburban',
  ),
  stop(
    'stop_suvarnabhumi_airport',
    'Suvarnabhumi Airport',
    13.6899,
    100.7501,
    'Suvarnabhumi Airport',
    'Airport terminal frontage with luggage-heavy travel demand around the clock',
    true,
    true,
    'interchange',
  ),
  stop(
    'stop_phetchaburi_mrt',
    'Phetchaburi',
    13.7478,
    100.5623,
    'MRT Phetchaburi / ARL Makkasan',
    'Airport Rail Link and MRT transfer area',
    true,
    true,
    'interchange',
  ),
];

const STOPS_BY_ID = Object.fromEntries(
  BANGKOK_STOPS.map((stopItem) => [stopItem.stopId, stopItem]),
) as Record<string, StopSeed>;

function getStop(stopId: string) {
  const stopItem = STOPS_BY_ID[stopId];

  if (!stopItem) {
    throw new Error(`Stop ${stopId} is not defined in Bangkok transit data.`);
  }

  return stopItem;
}

function polylineFromStops(stopIds: string[]) {
  return stopIds.map((stopId) => getStop(stopId).location);
}

function polylineFromPath(path: Array<string | Location>) {
  return path.map((node) => (typeof node === 'string' ? getStop(node).location : node));
}

function reverseDirection(
  directionId: DirectionId,
  origin: string,
  destination: string,
  directionLabel: string,
  stopIds: string[],
  polyline: Location[],
) {
  return {
    directionId,
    origin,
    destination,
    directionLabel,
    stopIds,
    polyline,
  };
}

function createBidirectionalRoute(config: {
  routeId: string;
  routeNumber: string;
  routeName: string;
  color: string;
  origin: string;
  destination: string;
  outboundDirection: string;
  inboundDirection: string;
  firstBusTime: string;
  lastBusTime: string;
  averageHeadwayMinutes: number;
  baseCruiseSpeedKmh: number;
  maxSpeedKmh: number;
  serviceLevel: RouteSeed['serviceLevel'];
  targetVehiclesPerDirection?: number;
  morningPeakFlow: RouteSeed['morningPeakFlow'];
  eveningPeakFlow: RouteSeed['eveningPeakFlow'];
  outboundStops: string[];
  outboundPath?: Array<string | Location>;
}): RouteSeed {
  const fallbackOutboundPolyline = polylineFromPath(
    config.outboundPath ?? config.outboundStops,
  );
  const inboundStops = [...config.outboundStops].reverse();
  const fallbackInboundPolyline = [...fallbackOutboundPolyline].reverse();
  const generatedRoadPolyline = GENERATED_ROAD_POLYLINES[config.routeId];
  const outboundPolyline =
    generatedRoadPolyline?.outbound?.length >= 2
      ? generatedRoadPolyline.outbound
      : fallbackOutboundPolyline;
  const inboundPolyline =
    generatedRoadPolyline?.inbound?.length >= 2
      ? generatedRoadPolyline.inbound
      : fallbackInboundPolyline;

  return {
    routeId: config.routeId,
    routeNumber: config.routeNumber,
    routeName: config.routeName,
    color: config.color,
    origin: config.origin,
    destination: config.destination,
    outboundDirection: config.outboundDirection,
    inboundDirection: config.inboundDirection,
    firstBusTime: config.firstBusTime,
    lastBusTime: config.lastBusTime,
    averageHeadwayMinutes: config.averageHeadwayMinutes,
    baseCruiseSpeedKmh: config.baseCruiseSpeedKmh,
    maxSpeedKmh: config.maxSpeedKmh,
    serviceLevel: config.serviceLevel,
    targetVehiclesPerDirection: config.targetVehiclesPerDirection,
    morningPeakFlow: config.morningPeakFlow,
    eveningPeakFlow: config.eveningPeakFlow,
    directions: {
      outbound: reverseDirection(
        'outbound',
        config.origin,
        config.destination,
        config.outboundDirection,
        config.outboundStops,
        outboundPolyline,
      ),
      inbound: reverseDirection(
        'inbound',
        config.destination,
        config.origin,
        config.inboundDirection,
        inboundStops,
        inboundPolyline,
      ),
    },
  };
}

export const BANGKOK_ROUTE_SEEDS: RouteSeed[] = [
  createBidirectionalRoute({
    routeId: 'route_26',
    routeNumber: '26',
    routeName: 'Min Buri - Victory Monument',
    color: '#F97316',
    origin: 'Min Buri',
    destination: 'Victory Monument',
    outboundDirection: 'Min Buri -> Victory Monument',
    inboundDirection: 'Victory Monument -> Min Buri',
    firstBusTime: '04:30',
    lastBusTime: '22:30',
    averageHeadwayMinutes: 9,
    baseCruiseSpeedKmh: 46,
    maxSpeedKmh: 68,
    serviceLevel: 'trunk',
    targetVehiclesPerDirection: 6,
    morningPeakFlow: 'outbound',
    eveningPeakFlow: 'inbound',
    outboundStops: [
      'stop_minburi_market',
      'stop_fashion_island',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_sanam_pao',
      'stop_victory_monument',
    ],
    outboundPath: [
      'stop_minburi_market',
      'stop_fashion_island',
      point(13.8329, 100.6564),
      point(13.8397, 100.6232),
      'stop_kasetsart_university',
      point(13.8343, 100.5814),
      'stop_ha_yaek_lat_phrao',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_sanam_pao',
      'stop_victory_monument',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_29',
    routeNumber: '29',
    routeName: 'Rangsit - Hua Lamphong',
    color: '#F26F22',
    origin: 'Rangsit',
    destination: 'Hua Lamphong',
    outboundDirection: 'Rangsit -> Hua Lamphong',
    inboundDirection: 'Hua Lamphong -> Rangsit',
    firstBusTime: '04:30',
    lastBusTime: '22:30',
    averageHeadwayMinutes: 10,
    baseCruiseSpeedKmh: 48,
    maxSpeedKmh: 70,
    serviceLevel: 'trunk',
    targetVehiclesPerDirection: 7,
    morningPeakFlow: 'inbound',
    eveningPeakFlow: 'outbound',
    outboundStops: [
      'stop_rangsit_market',
      'stop_don_mueang_airport',
      'stop_lak_si',
      'stop_bang_khen',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_sanam_pao',
      'stop_victory_monument',
      'stop_ratchathewi',
      'stop_siam',
      'stop_samyan',
      'stop_hua_lamphong',
    ],
    outboundPath: [
      'stop_rangsit_market',
      'stop_don_mueang_airport',
      'stop_lak_si',
      'stop_bang_khen',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_sanam_pao',
      'stop_victory_monument',
      'stop_ratchathewi',
      'stop_siam',
      'stop_samyan',
      'stop_hua_lamphong',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_34',
    routeNumber: '34',
    routeName: 'Bang Khen - Hua Lamphong',
    color: '#0EA5E9',
    origin: 'Bang Khen',
    destination: 'Hua Lamphong',
    outboundDirection: 'Bang Khen -> Hua Lamphong',
    inboundDirection: 'Hua Lamphong -> Bang Khen',
    firstBusTime: '04:00',
    lastBusTime: '22:30',
    averageHeadwayMinutes: 11,
    baseCruiseSpeedKmh: 44,
    maxSpeedKmh: 66,
    serviceLevel: 'local',
    targetVehiclesPerDirection: 5,
    morningPeakFlow: 'outbound',
    eveningPeakFlow: 'inbound',
    outboundStops: [
      'stop_bang_khen',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_sanam_pao',
      'stop_victory_monument',
      'stop_ratchathewi',
      'stop_siam',
      'stop_samyan',
      'stop_hua_lamphong',
    ],
    outboundPath: [
      'stop_bang_khen',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_sanam_pao',
      'stop_victory_monument',
      'stop_ratchathewi',
      'stop_siam',
      'stop_samyan',
      'stop_hua_lamphong',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_59',
    routeNumber: '59',
    routeName: 'Rangsit - Sanam Luang',
    color: '#DC2626',
    origin: 'Rangsit',
    destination: 'Sanam Luang',
    outboundDirection: 'Rangsit -> Sanam Luang',
    inboundDirection: 'Sanam Luang -> Rangsit',
    firstBusTime: '04:00',
    lastBusTime: '23:00',
    averageHeadwayMinutes: 8,
    baseCruiseSpeedKmh: 47,
    maxSpeedKmh: 68,
    serviceLevel: 'trunk',
    targetVehiclesPerDirection: 7,
    morningPeakFlow: 'inbound',
    eveningPeakFlow: 'outbound',
    outboundStops: [
      'stop_rangsit_market',
      'stop_don_mueang_airport',
      'stop_lak_si',
      'stop_bang_khen',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_victory_monument',
      'stop_democracy_monument',
      'stop_sanam_luang',
    ],
    outboundPath: [
      'stop_rangsit_market',
      'stop_don_mueang_airport',
      'stop_lak_si',
      'stop_bang_khen',
      'stop_kasetsart_university',
      'stop_chatuchak_park',
      'stop_saphan_khwai',
      'stop_ari',
      'stop_victory_monument',
      point(13.7611, 100.5218),
      'stop_democracy_monument',
      'stop_sanam_luang',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_145',
    routeNumber: '145',
    routeName: 'Mo Chit - Pak Nam (via Srinagarindra)',
    color: '#7C3AED',
    origin: 'Mo Chit',
    destination: 'Pak Nam',
    outboundDirection: 'Mo Chit -> Pak Nam',
    inboundDirection: 'Pak Nam -> Mo Chit',
    firstBusTime: '04:30',
    lastBusTime: '22:30',
    averageHeadwayMinutes: 10,
    baseCruiseSpeedKmh: 50,
    maxSpeedKmh: 74,
    serviceLevel: 'express',
    targetVehiclesPerDirection: 6,
    morningPeakFlow: 'outbound',
    eveningPeakFlow: 'inbound',
    outboundStops: [
      'stop_mochit_bus_terminal',
      'stop_ha_yaek_lat_phrao',
      'stop_lat_phrao',
      'stop_bang_kapi',
      'stop_ramkhamhaeng_24',
      'stop_udom_suk',
      'stop_bang_na',
      'stop_samrong',
      'stop_pak_nam',
    ],
    outboundPath: [
      'stop_mochit_bus_terminal',
      'stop_chatuchak_park',
      'stop_ha_yaek_lat_phrao',
      'stop_lat_phrao',
      point(13.7936, 100.5997),
      'stop_bang_kapi',
      'stop_ramkhamhaeng_24',
      point(13.7351, 100.6436),
      point(13.7132, 100.6468),
      point(13.6946, 100.6439),
      point(13.6835, 100.6298),
      'stop_udom_suk',
      'stop_bang_na',
      'stop_samrong',
      'stop_pak_nam',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_510',
    routeNumber: '510',
    routeName: 'Victory Monument - Thammasat Rangsit',
    color: '#0891B2',
    origin: 'Victory Monument',
    destination: 'Thammasat Rangsit',
    outboundDirection: 'Victory Monument -> Thammasat Rangsit',
    inboundDirection: 'Thammasat Rangsit -> Victory Monument',
    firstBusTime: '04:00',
    lastBusTime: '23:30',
    averageHeadwayMinutes: 12,
    baseCruiseSpeedKmh: 58,
    maxSpeedKmh: 80,
    serviceLevel: 'express',
    targetVehiclesPerDirection: 6,
    morningPeakFlow: 'inbound',
    eveningPeakFlow: 'outbound',
    outboundStops: [
      'stop_victory_monument',
      'stop_ari',
      'stop_saphan_khwai',
      'stop_chatuchak_park',
      'stop_kasetsart_university',
      'stop_lak_si',
      'stop_don_mueang_airport',
      'stop_rangsit_market',
      'stop_thammasat_rangsit',
    ],
    outboundPath: [
      'stop_victory_monument',
      'stop_ari',
      'stop_saphan_khwai',
      'stop_chatuchak_park',
      'stop_kasetsart_university',
      'stop_lak_si',
      'stop_don_mueang_airport',
      'stop_rangsit_market',
      'stop_thammasat_rangsit',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_511',
    routeNumber: '511',
    routeName: 'Pak Nam - Pinklao',
    color: '#2563EB',
    origin: 'Pak Nam',
    destination: 'Pinklao',
    outboundDirection: 'Pak Nam -> Pinklao',
    inboundDirection: 'Pinklao -> Pak Nam',
    firstBusTime: '04:00',
    lastBusTime: '23:00',
    averageHeadwayMinutes: 8,
    baseCruiseSpeedKmh: 54,
    maxSpeedKmh: 80,
    serviceLevel: 'express',
    targetVehiclesPerDirection: 7,
    morningPeakFlow: 'inbound',
    eveningPeakFlow: 'outbound',
    outboundStops: [
      'stop_pak_nam',
      'stop_samrong',
      'stop_bang_na',
      'stop_udom_suk',
      'stop_on_nut',
      'stop_phra_khanong',
      'stop_ekkamai',
      'stop_phrom_phong',
      'stop_asok',
      'stop_chitlom',
      'stop_pratunam',
      'stop_democracy_monument',
      'stop_pinklao',
    ],
    outboundPath: [
      'stop_pak_nam',
      'stop_samrong',
      'stop_bang_na',
      'stop_udom_suk',
      'stop_on_nut',
      'stop_phra_khanong',
      'stop_ekkamai',
      'stop_phrom_phong',
      'stop_asok',
      'stop_chitlom',
      'stop_pratunam',
      point(13.7568, 100.5301),
      'stop_democracy_monument',
      'stop_pinklao',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_8',
    routeNumber: '8',
    routeName: 'Bang Kapi - Wongwian Yai',
    color: '#16A34A',
    origin: 'Bang Kapi',
    destination: 'Wongwian Yai',
    outboundDirection: 'Bang Kapi -> Wongwian Yai',
    inboundDirection: 'Wongwian Yai -> Bang Kapi',
    firstBusTime: '04:30',
    lastBusTime: '22:30',
    averageHeadwayMinutes: 7,
    baseCruiseSpeedKmh: 44,
    maxSpeedKmh: 64,
    serviceLevel: 'trunk',
    targetVehiclesPerDirection: 8,
    morningPeakFlow: 'outbound',
    eveningPeakFlow: 'inbound',
    outboundStops: [
      'stop_bang_kapi',
      'stop_the_mall_bang_kapi',
      'stop_ramkhamhaeng_24',
      'stop_phetchaburi_mrt',
      'stop_pratunam',
      'stop_ratchathewi',
      'stop_siam',
      'stop_samyan',
      'stop_hua_lamphong',
      'stop_memorial_bridge',
      'stop_khlong_san',
      'stop_wongwian_yai',
    ],
    outboundPath: [
      'stop_bang_kapi',
      'stop_the_mall_bang_kapi',
      point(13.7628, 100.6368),
      point(13.7583, 100.6286),
      point(13.7546, 100.6205),
      'stop_ramkhamhaeng_24',
      point(13.7448, 100.6032),
      point(13.7425, 100.5968),
      point(13.7438, 100.5874),
      point(13.7461, 100.5754),
      'stop_phetchaburi_mrt',
      point(13.7489, 100.5538),
      'stop_pratunam',
      'stop_ratchathewi',
      'stop_siam',
      'stop_samyan',
      'stop_hua_lamphong',
      point(13.7386, 100.5091),
      'stop_memorial_bridge',
      point(13.7364, 100.5032),
      'stop_khlong_san',
      'stop_wongwian_yai',
    ],
  }),
  createBidirectionalRoute({
    routeId: 'route_77',
    routeNumber: '77',
    routeName: 'Bang Sue - Ekkamai',
    color: '#8B5CF6',
    origin: 'Bang Sue',
    destination: 'Ekkamai',
    outboundDirection: 'Bang Sue -> Ekkamai',
    inboundDirection: 'Ekkamai -> Bang Sue',
    firstBusTime: '05:00',
    lastBusTime: '23:00',
    averageHeadwayMinutes: 12,
    baseCruiseSpeedKmh: 46,
    maxSpeedKmh: 66,
    serviceLevel: 'local',
    targetVehiclesPerDirection: 5,
    morningPeakFlow: 'outbound',
    eveningPeakFlow: 'inbound',
    outboundStops: [
      'stop_bang_sue_grand_station',
      'stop_chatuchak_park',
      'stop_ha_yaek_lat_phrao',
      'stop_lat_phrao',
      'stop_sutthisan',
      'stop_huai_khwang',
      'stop_thailand_cultural_centre',
      'stop_rama_9',
      'stop_phetchaburi_mrt',
      'stop_asok',
      'stop_phrom_phong',
      'stop_ekkamai',
    ],
    outboundPath: [
      'stop_bang_sue_grand_station',
      'stop_chatuchak_park',
      'stop_ha_yaek_lat_phrao',
      'stop_lat_phrao',
      'stop_sutthisan',
      'stop_huai_khwang',
      'stop_thailand_cultural_centre',
      'stop_rama_9',
      'stop_phetchaburi_mrt',
      'stop_asok',
      'stop_phrom_phong',
      'stop_ekkamai',
    ],
  }),
];
